### ISSUE TITLE
Player List Block Audio and Video Controls

### ISSUE THREAD

**Issue by brunocalado** [saif-ellafi/foundryvtt-minimal-ui#104]
Hi!

Minimal UI blocks the use of the controls from AV.

![image](https://user-images.githubusercontent.com/4999783/192884305-d0dca7c3-887f-4b07-ac9a-9175d27bc492.png)

**Comment by CaosFR** [comment]
@saif-ellafi Same for me. Do you think you can solve it.

@brunocalado I use this macro for toogle the visibility of the player list.

```
if (ui.players.rendered) {

ui.players.close();

} else {

ui.players.render(true);

}
```

**Comment by brunocalado** [comment]
> Same for me since update to foundry v10 and the latest version of minimal-ui. @saif-ellafi Do you think you can solve it ? @brunocalado I use this macro for hide/unhide of the player list in the meantime of a fix.
> 
> ```
> if (ui.players.rendered) {
> 
> ui.players.close();
> 
> } else {
> 
> ui.players.render(true);
> 
> }
> ```

I'm moving to top or bottom to deal with this. But, this is a good solution.

**Comment by CaosFR** [comment]
@brunocalado How do you set the player list in other position ?

**Comment by brunocalado** [comment]
> @brunocalado How do you set the player list in other position ?

Not the player list. The cams. You can move then to top/bottom

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/198846798-256bb50a-e069-4645-b6e3-b1a74fdc4332.png)

**Comment by CaosFR** [comment]
Oh the dock, yes of course, I know it :) Thanks.

**Comment by saif-ellafi** [comment]
Thank you @CaosFR and @brunocalado for supporting here - I have released 1.5.1 with these fixes and your suggestions for thinner dock. appreciated if you let me know if it works. I have done minimal maintenance :)

**Comment by CaosFR** [comment]
@saif-ellafi I have test your update, thanks for your working.

For the size of the dock it's working. For the player list is not working, the player list is above the dock and now the options of miniumal for the player list dont work to (size, behaviour).
Sadly, for a strange raseon the options for the foundry logo dont work to now ! :(

![image](https://user-images.githubusercontent.com/37581932/198869422-291beab8-3592-49f0-9914-4963561963a1.png)

![image](https://user-images.githubusercontent.com/37581932/198869601-d5a7103e-5001-40e4-8cdb-5129a50b5944.png)

![image](https://user-images.githubusercontent.com/37581932/198869437-1ce9bb4f-427d-4b06-9be6-6e23bbd48811.png)
![image](https://user-images.githubusercontent.com/37581932/198869466-835a1785-c7c3-4f38-8a97-9bf58e5ba37e.png)

**Comment by saif-ellafi** [comment]
Hmmm @CaosFR - the logo I will see... but the player list is no problem for me. Are you sure you removed other conflicting UI modules or custom styles?
![image](https://user-images.githubusercontent.com/27952699/198871424-5b71cfba-ea19-4349-9c92-131a96266e7b.png)

**Comment by saif-ellafi** [comment]
I am not sure what is that button you have with a handshake

**Comment by saif-ellafi** [comment]
I have released 1.5.2 with some potential improvements, and fixed the logo issue with the camera dock enabled

**Comment by saif-ellafi** [comment]
For me it is working really well now. If there are still issues it is for sure a compatibility problem. I have disabled player list functionality when the camera is enabled, basically, so none of the functions will work but it will look normal without problems :)

**Comment by CaosFR** [comment]
The handshkae come from ItemsPile. With the 1.5.2 the foundry logo work now, thanks :)

The problem persist with the player list persist for me. All other module are disable.

**Comment by jacksands** [comment]
Same here, using alien system 
![image](https://user-images.githubusercontent.com/7229143/198888160-eefc512f-14e1-4cf2-90ca-1a6aa7f71f0b.png)

also hide completely also not working...
![image](https://user-images.githubusercontent.com/7229143/198888284-c4cd7992-cbad-4dc8-adc9-d325839a693a.png)

**Comment by saif-ellafi** [comment]
dang... checking

**Comment by jacksands** [comment]
don't worry man!  thanks for your amazing module!

we appreciate your effort!!!

**Comment by saif-ellafi** [comment]
Thanks, yeah. It really baffles me that it doesn't happen to me in 1.5.2
![image](https://user-images.githubusercontent.com/27952699/198888696-785e0e6b-3770-4767-a0ef-3a029b2a2deb.png)

**Comment by saif-ellafi** [comment]
I think I got it, it has to do with the hotbar position, you too seem to have the hotbar on the right

**Comment by saif-ellafi** [comment]
Alright @brunocalado @jacksands @CaosFR -- It was much harder than I had originally thought :) 
I think I could fix it now, phew. I really hope so. Plenty of code changes, if you could take a look, really appreciated.
Fixed on version 1.5.3

**Comment by saif-ellafi** [comment]
Ok, fixed for real in 1.5.4 , I hope!!!

**Comment by jacksands** [comment]
PERFECT!!

![image](https://user-images.githubusercontent.com/7229143/198903562-f56791d6-8f21-45f4-9bf4-0214b916b647.png)

![image](https://user-images.githubusercontent.com/7229143/198903624-cb19ed09-3b7d-4e57-9309-d7837daa0fea.png)


tks my friend!

**Comment by saif-ellafi** [comment]
have fun!!!

**Comment by CaosFR** [comment]
![DnDIWin-PLATE-500x500](https://user-images.githubusercontent.com/37581932/198982516-99162dea-743c-436e-a3a5-e8d60763e889.jpg)

@saif-ellafi Thanks :)
