### ISSUE TITLE
Incompatibility with MyTab mod

### ISSUE THREAD

**Issue by apoapostolov** [saif-ellafi/foundryvtt-minimal-ui#29]
MyTab mod can skin the anvil icon just as the added functionality and takes priority to it. This makes it hard for people who already have configured custom anvil icon to use the rest of the Minimal UI mod.

Please add the option not to mod the anvil icon at all, so MyTab can take priority there.

**Comment by saif-ellafi** [comment]
Thanks for reporting this, will take a look.

**Comment by saif-ellafi** [comment]
Fixed in 0.8.8 please confirm!!

**Comment by apoapostolov** [comment]
Seems still an issue, The Minimal UI anvil still overwrites the MyTab icon.

**Comment by saif-ellafi** [comment]
> Seems still an issue, The Minimal UI anvil still overwrites the MyTab custom image.

But how? :(

![image](https://user-images.githubusercontent.com/27952699/116223295-ae181180-a74f-11eb-9ea5-9ad80ea72ce6.png)

![image](https://user-images.githubusercontent.com/27952699/116223370-bff9b480-a74f-11eb-8900-437c03140b95.png)

**Comment by saif-ellafi** [comment]
Could you confirm @apoapostolov ?

**Comment by apoapostolov** [comment]
MyTab doesn't grab any priority on my side.

**Comment by apoapostolov** [comment]
OK, today I tested again and this time MyTab properly got priority. 

![image](https://user-images.githubusercontent.com/4083812/116305741-df72fa80-a7ac-11eb-96ce-63e2e2db695a.png)
