### ISSUE TITLE
Left Controls size does not change

### ISSUE THREAD

**Issue by Chryron** [saif-ellafi/foundryvtt-minimal-ui#88]
After the latest update to foundry yesterday, the left control panel returned to its standard size. Changing the size between small and standard in the minimal ui configuration page has no effect.

![image](https://user-images.githubusercontent.com/43299520/156273058-0cae9d78-f446-43e7-8fc5-9ffc3b68680f.png)
![image](https://user-images.githubusercontent.com/43299520/156273051-4a972b5b-ffab-456e-86e2-0425174c0403.png)

**Comment by MorganVergara** [comment]
I would like to second this. My environment is:

Foundry v9.251
DnD5e 1.5.7
Active Modules:

![image](https://user-images.githubusercontent.com/30846057/156275137-e6cbd7e5-3060-4496-984c-904db231b4c1.png)

Thanks!

**Comment by sigshot552** [comment]
![image](https://user-images.githubusercontent.com/66184944/156288522-0227aeb6-1803-4d52-9826-d3465e884116.png)

can confirm the same issue

**Comment by saif-ellafi** [comment]
Dear all, Minimal UI should now work well with the latest Foundry version. Please let me know if otherwise.

**Comment by GojimboGoGo** [comment]
It looks very nice, thanks!

![image](https://user-images.githubusercontent.com/31174444/156496605-80684077-8496-40d0-902f-170ec1abd92b.png)

**Comment by MorganVergara** [comment]
Hmm.. buttons are now the correct size, with the correct margins between them. Two problems remain:

- The gap at the top is still quite large, and,
- When the buttons are large and spill over into another column, they are still clipped.

![image](https://user-images.githubusercontent.com/30846057/156582430-3bd7a5ff-39c3-4471-848c-5e1f166db39e.png)

I usually keep the buttons small, but I thought this was worth mentioning for the sake of completeness.

Thanks!

**Comment by saif-ellafi** [comment]
Thanks @MorganVergara but I cannot reproduce this overflow on the latest version. The Margin top did not change from previous version. I don't remember why I added that space on top but it is not new.

Regarding the Overflow, I cannot reproduce that. Can you try without modules?

**Comment by saif-ellafi** [comment]
Closing. Please follow other issues in separate issues accordingly. This fix was related to the latest Stable 3 version of Foundry. Thank you  all.

**Comment by MorganVergara** [comment]
It's a bit difficult to reproduce without modules since the additional
modules are what is causing the overflow to happen :) Without modules,
there's not enough buttons there to overflow. In any event, it's not a big
deal since the main reason I use minimal UI is to get the smaller buttons,
which don't lead to overflowing.  Thanks for fixing the other issue, though!

Morgan

**Comment by saif-ellafi** [comment]
Thanks @MorganVergara - could you open a new issue to address that specifically? With the list of modules that add up to that issue.
